---
- name: Install 389ds packages (apt)
  apt:
    name: "{{ item }}"
    state: "{{ dirsrv_package_state }}"
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"
  with_items:
    - "{{ dirsrv_packages }}"
  tags:
    - install

- name: install epel-release for CentOS
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: Install 389ds packages (yum)
  yum:
    name: "{{ item }}"
    state: "{{ dirsrv_package_state }}"
  when: ansible_os_family == "RedHat"
  with_items:
    - "{{ dirsrv_packages }}"
  tags:
    - install
# vim:ft=ansible:
